#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression --message="Installing dependencies..." --weight=6

ynh_install_nodejs --nodejs_version=$nodejs_version

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir=$install_dir

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# INSTALL ETHERPAD
#=================================================
ynh_script_progression --message="Installing $app..." --weight=60

pushd $install_dir
 	ynh_use_nodejs
 	ynh_exec_warn_less ynh_exec_as $app env $ynh_node_load_PATH bin/installDeps.sh
popd

#=================================================
# MODIFY A CONFIG FILE
#=================================================
ynh_script_progression --message="Configuring $app..." --weight=6

ynh_add_config --template="settings.json" --destination="$install_dir/settings.json"
chmod 400 "$install_dir/settings.json"
chown $app:$app "$install_dir/settings.json"

if [ "$export" = "abiword" ]
then
	# Get AbiWord binary path
	abiword_path=`which abiword`
	# Set the path of AbiWord into Etherpad config
	ynh_replace_string --match_string="\"abiword\" : null" --replace_string="\"abiword\" : \"$abiword_path\"" --target_file="$install_dir/settings.json"
elif [ "$export" = "libreoffice" ]
then
	# Get soffice binary path
	soffice_path=`which soffice`
	# Set the path of soffice into Etherpad config
	ynh_replace_string --match_string="\"soffice\" : null" --replace_string="\"soffice\" : \"$soffice_path\"" --target_file="$install_dir/settings.json"
fi
ynh_store_file_checksum --file="$install_dir/settings.json"

ynh_add_config --template="credentials.json" --destination="$install_dir/credentials.json"
chmod 400 "$install_dir/credentials.json"
chown $app:$app "$install_dir/credentials.json"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression --message="Configuring a systemd service..." --weight=4

# Create a dedicated systemd config
ynh_add_systemd_config

# Create a dedicated NGINX config
ynh_add_nginx_config

# Use logrotate to manage application logfile(s)
ynh_use_logrotate

yunohost service add $app --description="Collaborative editor" --log="/var/log/$app/$app.log"

#=================================================
# MODIFY A CONFIG FILE
#=================================================
ynh_script_progression --message="Configuring $app..." --weight=6

abiword_path="null"
soffice_path="null"

if [[ "$export" == "abiword" ]]
then
    abiword_path="\"$(which abiword)\""
elif [[ "$export" == "libreoffice" ]]
then
    soffice_path="\"$(which soffice)\""
fi

ynh_add_config --template="settings.json" --destination="$install_dir/settings.json"
ynh_add_config --template="credentials.json" --destination="$install_dir/credentials.json"

chmod 600 "$install_dir/settings.json"
chown $app:$app "$install_dir/settings.json"

chmod 600 "$install_dir/credentials.json"
chown $app:$app "$install_dir/credentials.json"

#=================================================
# INSTALL ETHERPAD
#=================================================
#ynh_script_progression --message="Installing $app..." --weight=10

#pushd $install_dir
# 	ynh_use_nodejs
# 	ynh_exec_warn_less ynh_exec_as $app env $ynh_node_load_PATH ETHERPAD_PRODUCTION=true bin/installDeps.sh
#popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=6

# Start a systemd service
ynh_systemd_action --service_name=$app --action=restart --log_path=systemd --line_match="Your Etherpad version is"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of Etherpad completed" --last
