#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_nodejs_install

#=================================================
# CREATE REDIS DATABASE
#=================================================
ynh_script_progression "Creating a Redis database..."

redis_db=$(ynh_redis_get_free_db)
ynh_app_setting_set --key=redis_db --value="$redis_db"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir=$install_dir

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_systemd

ynh_config_add_nginx

ynh_config_add_logrotate

yunohost service add $app --description="Collaborative editor" --log="/var/log/$app/$app.log"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

abiword_path="null"
soffice_path="null"

if [[ "$export" == "abiword" ]]
then
    abiword_path="\"$(which abiword)\""
elif [[ "$export" == "libreoffice" ]]
then
    soffice_path="\"$(which soffice)\""
fi

ynh_config_add --template="settings.json" --destination="$install_dir/settings.json"
ynh_config_add --template="credentials.json" --destination="$install_dir/credentials.json"

#=================================================
# INSTALL ETHERPAD
#=================================================
ynh_script_progression "Installing $app..."

pushd $install_dir
    ynh_hide_warnings corepack enable && corepack prepare pnpm@latest --activate
    ynh_hide_warnings pnpm --recursive i --production
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action=restart --log_path=systemd --wait_until="Your Etherpad version is"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of Etherpad completed"
